-- Database Schema for Bon Appetite Cafe and Restro System

-- Drop tables if they exist
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS menu_items CASCADE;
DROP TABLE IF EXISTS system_settings CASCADE;
DROP TABLE IF EXISTS waiting_list CASCADE;
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS tables CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP SEQUENCE IF EXISTS order_num_seq CASCADE;
DROP SEQUENCE IF EXISTS invoice_num_seq CASCADE;

-- 1. Users Table
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  role VARCHAR(50) DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Tables Table
CREATE TABLE tables (
  id INT PRIMARY KEY,
  table_name VARCHAR(100) NOT NULL,
  capacity INT NOT NULL,
  available BOOLEAN DEFAULT TRUE,
  qr_token_hash VARCHAR(64) DEFAULT '',
  status VARCHAR(50) DEFAULT 'available' CHECK (status IN ('available', 'occupied', 'reserved', 'cleaning'))
);

-- Populate initial physical tables configuration with hashed tokens
-- SHA-256 hashes of standard secure tokens:
-- Table 1 Raw Token: tok_table1_secure_xyz1234567890abc -> Hash: 90cabbd86a48b459fabbf69ce97667a96d1cee0080ad7989955f7955560c0af3
-- Table 2 Raw Token: tok_table2_secure_abc1234567890xyz -> Hash: bc9788185c2b5ba7e492aaf42af8385abbc34f154fd3c889b3594ca5e630623e
-- Table 3 Raw Token: tok_table3_secure_qwe1234567890rty -> Hash: 7ed6f91e3a3d8a3a7cc5f7a234ca718f995640ccb8a745dd4037abd73273743e
-- Table 4 Raw Token: tok_table4_secure_rty1234567890uio -> Hash: cc8970a808f96feda05d1a8b4ef71da79ec3a74e0b1033f45394e8a652677695
-- Table 5 Raw Token: tok_table5_secure_uio1234567890pml -> Hash: 73509df31f867d094ce720dd03bfc8715b9c61c5fcb2d709492a05e22f9e71d4
-- Table 6 Raw Token: tok_table6_secure_pml1234567890qwe -> Hash: 071569dd69f37db96d3ff8e90a649841ab8720ca1062469d4bbe810c65eb9647
INSERT INTO tables (id, table_name, capacity, available, qr_token_hash, status) VALUES
(1, 'Table 1', 2, TRUE, '90cabbd86a48b459fabbf69ce97667a96d1cee0080ad7989955f7955560c0af3', 'available'),
(2, 'Table 2', 2, TRUE, 'bc9788185c2b5ba7e492aaf42af8385abbc34f154fd3c889b3594ca5e630623e', 'available'),
(3, 'Table 3', 4, TRUE, '7ed6f91e3a3d8a3a7cc5f7a234ca718f995640ccb8a745dd4037abd73273743e', 'available'),
(4, 'Table 4', 4, TRUE, 'cc8970a808f96feda05d1a8b4ef71da79ec3a74e0b1033f45394e8a652677695', 'available'),
(5, 'Table 5', 6, TRUE, '73509df31f867d094ce720dd03bfc8715b9c61c5fcb2d709492a05e22f9e71d4', 'available'),
(6, 'Table 6', 8, TRUE, '071569dd69f37db96d3ff8e90a649841ab8720ca1062469d4bbe810c65eb9647', 'available');

-- 3. System Settings Table
CREATE TABLE system_settings (
  key VARCHAR(100) PRIMARY KEY,
  value VARCHAR(255) NOT NULL,
  description TEXT
);

INSERT INTO system_settings (key, value, description) VALUES
('gst_percentage', '18', 'GST Tax percentage applied to orders'),
('service_charge', '150', 'Service charge value'),
('service_charge_type', 'fixed', 'fixed, percentage, or disabled'),
('cafe_name', 'Bon Appetite Cafe and Restro', 'Name of the cafe display'),
('upi_id', 'ranadwarkesh9-1@okicici', 'UPI address for receiving customer payments');

-- 4. Menu Items Table (With Soft Delete support)
CREATE TABLE menu_items (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) UNIQUE NOT NULL,
  price INT NOT NULL CHECK (price >= 0),
  available BOOLEAN DEFAULT TRUE,
  preparation_time_minutes INT DEFAULT 15 CHECK (preparation_time_minutes >= 0),
  deleted BOOLEAN DEFAULT FALSE
);

-- Seed Menu Items
INSERT INTO menu_items (name, price, available, preparation_time_minutes) VALUES
('Grand Espresso Macchiato', 450, TRUE, 5),
('Champagne Truffle Latte', 650, TRUE, 7),
('Rose Gold Affogato', 750, TRUE, 8),
('Cold Brew Reserve', 550, TRUE, 5),
('Truffle Tagliolini', 1850, TRUE, 15),
('Wild Mushroom Risotto', 1450, TRUE, 15),
('Wagyu Ribeye Steak (Mock Special)', 3850, TRUE, 20),
('Saffron Garlic Salmon', 2450, TRUE, 18),
('Golden Foil Cheesecake', 950, TRUE, 6),
('Pistachio Paris-Brest', 850, TRUE, 6),
('Lava Chocolate Souffle', 890, TRUE, 12),
('Madagascar Creme Brulee', 750, TRUE, 8),
('Saffron Mango Mocktail', 650, TRUE, 6),
('Lavender Honey Tonic', 590, TRUE, 5),
('Smoked Wood Old Fashioned', 750, TRUE, 8),
('Rosewater Berry Fizz', 690, TRUE, 6);

-- 5. Reservations Table
CREATE TABLE reservations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  reservation_date DATE NOT NULL,
  reservation_time VARCHAR(50) NOT NULL,
  guests INT NOT NULL,
  table_number VARCHAR(100), -- Holds comma-separated table numbers if combined (e.g. "Table 1, Table 2")
  status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'rejected', 'cancelled', 'completed')),
  verification_token VARCHAR(255),
  email_status VARCHAR(50) DEFAULT 'pending' CHECK (email_status IN ('pending', 'sent', 'failed')),
  whatsapp_status VARCHAR(50) DEFAULT 'pending' CHECK (whatsapp_status IN ('pending', 'sent', 'failed')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 6. Waiting List Table
CREATE TABLE waiting_list (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255) NOT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  time VARCHAR(50) NOT NULL,
  guests INT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Sequences for order numbers and invoice numbers
CREATE SEQUENCE order_num_seq START WITH 1;
CREATE SEQUENCE invoice_num_seq START WITH 1;

-- 7. Orders Table
CREATE TABLE orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number VARCHAR(20) NOT NULL UNIQUE DEFAULT 'BON-' || lpad(nextval('order_num_seq')::text, 4, '0'),
  invoice_number VARCHAR(30) UNIQUE,
  customer_name VARCHAR(255) NOT NULL,
  phone VARCHAR(50),
  table_number VARCHAR(100) NOT NULL,
  reservation_id UUID REFERENCES reservations(id) ON DELETE SET NULL,
  subtotal INT NOT NULL CHECK (subtotal >= 0),
  tax_amount INT NOT NULL CHECK (tax_amount >= 0),
  service_charge INT NOT NULL CHECK (service_charge >= 0),
  final_amount INT NOT NULL CHECK (final_amount >= 0),
  payment_status VARCHAR(50) DEFAULT 'pending_verification' CHECK (payment_status IN ('pending_payment', 'pending_verification', 'paid', 'failed', 'expired')),
  order_status VARCHAR(50) DEFAULT 'pending' CHECK (order_status IN ('pending', 'confirmed', 'preparing', 'ready', 'served', 'cancelled')),
  upi_transaction_id VARCHAR(100) UNIQUE,
  estimated_ready_time INT DEFAULT 15 CHECK (estimated_ready_time >= 0),
  order_session_token_hash VARCHAR(64) NOT NULL,
  payment_expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  verification_time TIMESTAMP WITH TIME ZONE,
  verified_by VARCHAR(255),
  payment_reference VARCHAR(255),
  confirmed_at TIMESTAMP WITH TIME ZONE,
  preparing_at TIMESTAMP WITH TIME ZONE,
  ready_at TIMESTAMP WITH TIME ZONE,
  served_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  cancelled_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 8. Order Items Table (linked to menu_items name to allow read even if name is updated, but with CASCADE block)
CREATE TABLE order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  food_item VARCHAR(255) REFERENCES menu_items(name) ON DELETE RESTRICT,
  quantity INT NOT NULL CHECK (quantity > 0),
  price INT NOT NULL CHECK (price >= 0),
  special_instruction TEXT
);

-- 9. Audit Logs Table
CREATE TABLE audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  actor VARCHAR(255) NOT NULL,
  action VARCHAR(255) NOT NULL,
  details TEXT,
  ip_address VARCHAR(100),
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance and lookup
CREATE INDEX idx_reservations_email ON reservations(email);
CREATE INDEX idx_reservations_status ON reservations(status);
CREATE INDEX idx_reservations_date_time ON reservations(reservation_date, reservation_time);
CREATE INDEX idx_waiting_list_priority ON waiting_list(created_at ASC);
CREATE INDEX idx_orders_table_number ON orders(table_number);
CREATE INDEX idx_orders_created_at ON orders(created_at);
CREATE INDEX idx_orders_order_status ON orders(order_status);
CREATE INDEX idx_orders_payment_status ON orders(payment_status);

-- Prevent double booking trigger
CREATE OR REPLACE FUNCTION check_table_overlap()
RETURNS TRIGGER AS $$
DECLARE
  table_item TEXT;
  overlap_count INT;
BEGIN
  IF NEW.table_number IS NULL OR NEW.status IN ('cancelled', 'rejected') THEN
    RETURN NEW;
  END IF;

  FOR table_item IN SELECT regexp_split_to_table(NEW.table_number, ',\s*') LOOP
    SELECT COUNT(*) INTO overlap_count
    FROM reservations r
    WHERE r.id != NEW.id
      AND r.reservation_date = NEW.reservation_date
      AND r.reservation_time = NEW.reservation_time
      AND r.status IN ('confirmed', 'pending')
      AND EXISTS (
        SELECT 1
        FROM regexp_split_to_table(r.table_number, ',\s*') assigned_table
        WHERE assigned_table = table_item
      );
    
    IF overlap_count > 0 THEN
      RAISE EXCEPTION 'Table % is already reserved for % at %.', table_item, NEW.reservation_date, NEW.reservation_time;
    END IF;
  END LOOP;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER prevent_double_booking
BEFORE INSERT OR UPDATE ON reservations
FOR EACH ROW
EXECUTE FUNCTION check_table_overlap();
